CREATE ROLE skyvia_sync WITH LOGIN PASSWORD 'mnlJGPgsaBujhXZRWcnlzTM7qHNJ' NOINHERIT;
GRANT USAGE ON SCHEMA public TO skyvia_sync;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO skyvia_sync;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO skyvia_sync;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO skyvia_sync;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO skyvia_sync;