-- Restore dealer rep/manager assignments made by Will Grisack on 2026-07-02
-- that were lost in the Supabase server migration.
-- Matches dealers by name (case-insensitive) and reps/managers by name.

WITH assignments (company_name, rep_name, manager_name) AS (
  VALUES
    ('Rudy''s',                                    'Dave Ervin',        'Mateo De Lisa'),
    ('Baer''s Sarasota',                           'Brent Holbrook',    'Will Grisack'),
    ('Oskar Huber Furniture & Design',             'Shindell- Beach',   'Mateo De Lisa'),
    ('Cedar Hill Furniture',                       'Shindell - PA/OH',  'Mateo De Lisa'),
    ('Home Point',                                 'Brad Robertson',    'Mateo De Lisa'),
    ('Willis Furniture Co Inc',                    'Brad Robertson',    'Mateo De Lisa'),
    ('Perfect Furnishings',                        'Shindell- Beach',   'Mateo De Lisa'),
    ('Lower Valley Furniture',                     'Shindell - PA/OH',  'Mateo De Lisa'),
    ('Great Bridge Furniture',                     'Brad Robertson',    'Mateo De Lisa'),
    ('B&H Furniture',                              'Brad Robertson',    'Mateo De Lisa'),
    ('Bruxvoorts Home Center',                     'House',             'House'),
    ('Gabe''s',                                    'Brad Robertson',    'Mateo De Lisa'),
    ('Arkansas Furniture',                         'House',             'House'),
    ('D. Marie',                                   'Shindell- Beach',   'Mateo De Lisa'),
    ('Creative Displays & Designs Inc',            'Shindell - PA/OH',  'Mateo De Lisa'),
    ('Model Home Interiors',                       'Brad Robertson',    'Mateo De Lisa'),
    ('Blackstone Emporium Inc',                    'Brad Robertson',    'Mateo De Lisa'),
    ('Refreshed Coastal Inspired Living',          'Brad Robertson',    'Mateo De Lisa'),
    ('Bryan''s Furniture Interiors',               'Shindell - PA/OH',  'Mateo De Lisa'),
    ('The Light House of Lewes',                   'Shindell- Beach',   'Mateo De Lisa'),
    ('Taylor''s Furniture',                        'Shindell - PA/OH',  'Mateo De Lisa'),
    ('Countryside Furniture, Inc.',                'Shindell - PA/OH',  'Mateo De Lisa'),
    ('Teeples Investments',                        'House',             'House'),
    ('Ramirez Furniture, LLC',                     'Stewart Hunt',      'Will Grisack'),
    ('Curles Mattress Outlet',                     'Dave Ervin',        'Mateo De Lisa'),
    ('Middleman Mattress Corp/Furniture To Go',    'Peter Avella',      'Mateo De Lisa'),
    ('Terrazas Furniture Inc.',                    'Stewart Hunt',      'Will Grisack'),
    ('Dreier Marketing & Sales',                   'Stewart Hunt',      'Will Grisack'),
    ('James Craig Furnishings',                    'Stewart Hunt',      'Will Grisack'),
    ('Acker Appliance, Inc.',                      'Bruce Quillen',     'Will Grisack'),
    ('Angie Furniture LLC',                        'Stewart Hunt',      'Will Grisack'),
    ('Stamford Tire Company, LLC',                 'Stewart Hunt',      'Will Grisack'),
    ('Ronald Fowler',                              'Stewart Hunt',      'Will Grisack'),
    ('Urbano Furniture Shop',                      'Skip Camillo',      'House'),
    ('COINANDCOMPA',                               'Brent Holbrook',    'Will Grisack'),
    ('Alejandro Vega',                             'Stewart Hunt',      'Will Grisack'),
    ('James C. Moore, Inc.',                       'Stewart Hunt',      'Will Grisack'),
    ('Harris Furniture Co., Inc.',                 'Skip Camillo',      'House'),
    ('Luan Furniture',                             'Stewart Hunt',      'Will Grisack'),
    ('SimpleTronics LLC',                          'Stewart Hunt',      'Will Grisack'),
    ('Top Choice Movers. Inc.',                    'Brent Holbrook',    'Will Grisack'),
    ('Currations Furniture and Design',            'Mike Durham',       'Will Grisack'),
    ('The Bargain House',                          'Peter Avella',      'Mateo De Lisa'),
    ('Clifton Ventures Inc.',                      'Brad Robertson',    'Mateo De Lisa'),
    ('Badcocks Economy Furniture Store, Inc.',     'Brent Holbrook',    'Will Grisack'),
    ('Furnikoure, LLC',                            'Mike Durham',       'Will Grisack'),
    ('Ralph''s Interiors',                         'Brent Holbrook',    'Will Grisack'),
    ('DMS Sales',                                  'Brent Holbrook',    'Will Grisack'),
    ('Brenmark, Inc.',                             'Brent Holbrook',    'Will Grisack'),
    ('Lazman Trading LLC',                         'Stewart Hunt',      'Will Grisack'),
    ('Quality Electronics',                        'Stewart Hunt',      'Will Grisack'),
    ('Thomson TV',                                 'Dave Ervin',        'Mateo De Lisa'),
    ('Happy Homes Industries LLC',                 'Stewart Hunt',      'Will Grisack'),
    ('BTZ Audio/Video LLC',                        'Stewart Hunt',      'Will Grisack'),
    ('ESD Technologies, LLC',                      'Stewart Hunt',      'Will Grisack'),
    ('National Furniture Supply',                  'Bruce Quillen',     'Will Grisack'),
    ('The Furniture Outlet',                       'Stewart Hunt',      'Will Grisack'),
    ('Luke and Brandi Gillis Customer',            'House',             'House'),
    ('BUILDERS MODEL FURN',                        'Brent Holbrook',    'Will Grisack'),
    ('Sunset Sleep Center Inc.',                   'Dave Ervin',        'Mateo De Lisa'),
    ('Tracys Furniture Inc',                       'House',             'House'),
    ('Best Buy Home Furniture Inc.',               'Stewart Hunt',      'Will Grisack'),
    ('Paradise Home Decor',                        'Brent Holbrook',    'Will Grisack'),
    ('Emerald Coast Sleep Center, LLC',            'Bruce Quillen',     'Will Grisack'),
    ('Midways Furniture Warehouse',                'Brad Robertson',    'Mateo De Lisa'),
    ('Modahf',                                     'Stewart Hunt',      'Will Grisack'),
    ('Crown Furniture Inc.',                       'Stewart Hunt',      'Will Grisack'),
    ('The Appliance Place',                        'Brad Robertson',    'Mateo De Lisa'),
    ('Rich Bedding LLC',                           'Mike Durham',       'Will Grisack'),
    ('Dorwin Dawson Associates Inc',               'Peter Avella',      'Mateo De Lisa'),
    ('IQueue Media Company, LLC',                  'Stewart Hunt',      'Will Grisack'),
    ('INI Inc',                                    'Brad Robertson',    'Mateo De Lisa'),
    ('McCurry Enterprises Inc.',                   'Bruce Quillen',     'Will Grisack'),
    ('TIDI, Inc.',                                 'Brad Robertson',    'Mateo De Lisa'),
    ('Haven Design',                               'Brent Holbrook',    'Will Grisack'),
    ('ABC Flooring and Home, LLC',                 'Skip Camillo',      'House'),
    ('Kreative Konnectionz Audio & Video LLC',     'Stewart Hunt',      'Will Grisack'),
    ('Chavis Furniture, LLC',                      'Bruce Quillen',     'Will Grisack'),
    ('LIVING QUARTERS',                            'Peter Avella',      'Mateo De Lisa'),
    ('KOI Furniture and More, Inc.',               'Brent Holbrook',    'Will Grisack'),
    ('Dave Price',                                 'Stewart Hunt',      'Will Grisack'),
    ('SWC Sales',                                  'Stewart Hunt',      'Will Grisack'),
    ('DESIGN STUDIO OF SOMERVILLE',               'Peter Avella',      'Mateo De Lisa'),
    ('Puente''s Furniture & Appliance',            'Stewart Hunt',      'Will Grisack'),
    ('B&F Consulting',                             'Dave Ervin',        'Mateo De Lisa'),
    ('Hometown Furnishings',                       'Skip Camillo',      'House'),
    ('Kinetic Holdings LLC',                       'Dave Ervin',        'Mateo De Lisa'),
    ('Interactive Interiors',                      'Dave Ervin',        'Mateo De Lisa'),
    ('Nalley''s Mattress Center, Inc.',            'Dave Ervin',        'Mateo De Lisa'),
    ('JSSC, LLC',                                  'Bruce Quillen',     'Will Grisack'),
    ('Ridge Connect, LLC',                         'Bruce Quillen',     'Will Grisack'),
    ('Hudson''s Sarasota',                         'Brent Holbrook',    'Will Grisack'),
    ('Boothe Appliance, Inc.',                     'Bruce Quillen',     'Will Grisack'),
    ('Home Fashion Interiors',                     'Bruce Quillen',     'Will Grisack'),
    ('Landes Furniture of Rotan LP',               'Stewart Hunt',      'Will Grisack'),
    ('STUCKEYBROS',                                'Dave Ervin',        'Mateo De Lisa'),
    ('Johnsons Furniture & Mattress',              'Stewart Hunt',      'Will Grisack'),
    ('Niposul, Inc.',                              'Stewart Hunt',      'Will Grisack'),
    ('K&ACoastalDesign',                           'Brent Holbrook',    'Will Grisack'),
    ('Wallace Variety, Inc.',                      'Dave Ervin',        'Mateo De Lisa'),
    ('Four Corners Home',                          'Dave Ervin',        'Mateo De Lisa'),
    ('HVT Investments LLC',                        'Stewart Hunt',      'Will Grisack'),
    ('Spirit 217, LLC',                            'Shindell - PA/OH',  'Mateo De Lisa'),
    ('SOUTHCOAST',                                 'Brad Robertson',    'Mateo De Lisa'),
    ('Billy Bob Inc.',                             'Skip Camillo',      'House'),
    ('Into the West',                              'Stewart Hunt',      'Will Grisack'),
    ('Woodcocks Appliances',                       'Brent Holbrook',    'Will Grisack'),
    ('Palcat, LLC dba Rosen Vacations',            'Sergio Hospitality','Sergio'),
    ('George Bloom Furniture',                     'Shindell- Beach',   'Mateo De Lisa'),
    ('R. Garza Investments LLC',                   'Stewart Hunt',      'Will Grisack'),
    ('Shahabi Interiors, Inc',                     'Brad Robertson',    'Mateo De Lisa'),
    ('Kodiak Building Partners',                   'Stewart Hunt',      'Will Grisack'),
    ('Carriage Inc.',                              'Stewart Hunt',      'Will Grisack'),
    ('All About Wicker, LLC',                      'Brent Holbrook',    'Will Grisack'),
    ('Premium Appliance Rentals LLC',              'Stewart Hunt',      'Will Grisack'),
    ('Skero''s Furniture, Inc.',                   'Stewart Hunt',      'Will Grisack'),
    ('Intelligent Electronic Systems, Inc.',       'Stewart Hunt',      'Will Grisack'),
    ('Bassec, LLC',                                'Stewart Hunt',      'Will Grisack'),
    ('Welcome Travelers Furniture',                'Mike Durham',       'Will Grisack'),
    ('Bay Area Appliance',                         'Brent Holbrook',    'Will Grisack'),
    ('Royal Furniture and Rugs Inc.',              'Stewart Hunt',      'Will Grisack'),
    ('B & B of Brevard LLC',                       'Stewart Hunt',      'Will Grisack'),
    ('Skytop Group, Inc.',                         'Skip Camillo',      'House'),
    ('Sports Center, Inc.',                        'Dave Ervin',        'Mateo De Lisa'),
    ('Marvin Rodriguez',                           'Stewart Hunt',      'Will Grisack'),
    ('Watson''s 87 Furniture, Inc.',               'Shindell - PA/OH',  'Mateo De Lisa'),
    ('America Wholesale Furniture',                'Stewart Hunt',      'Will Grisack'),
    ('Consignment Furniture - Gulf Brz',           'Bruce Quillen',     'Will Grisack'),
    ('Batchco One, LLC',                           'Brent Holbrook',    'Will Grisack'),
    ('Irving Street Appliance, Inc.',              'Stewart Hunt',      'Will Grisack'),
    ('Burlington Furniture Co., Inc.',             'Skip Camillo',      'House'),
    ('Sunnyland Outdoor Living',                   'Stewart Hunt',      'Will Grisack'),
    ('Alabama Pool and Spa Supply, Inc.',          'Bruce Quillen',     'Will Grisack'),
    ('SETX NAS Investment',                        'Stewart Hunt',      'Will Grisack'),
    ('Curtis Home Stores, LLC',                    'Bruce Quillen',     'Will Grisack'),
    ('Digitalholics, LLC',                         'Stewart Hunt',      'Will Grisack'),
    ('Infinity Security Group, Inc',               'Stewart Hunt',      'Will Grisack'),
    ('Ruby & Quiri, Inc.',                         'Peter Avella',      'Mateo De Lisa'),
    ('City Furniture, Inc',                        'Brent Holbrook',    'Will Grisack'),
    ('Pulaski Appliance',                          'Brad Robertson',    'Mateo De Lisa'),
    ('L & W Appliance Repair LLC',                 'Stewart Hunt',      'Will Grisack'),
    ('Best Prices Appliances, LLC',                'Mike Durham',       'Will Grisack'),
    ('TM Royal, LLC',                              'Stewart Hunt',      'Will Grisack'),
    ('Integrated System Design Texas',             'Stewart Hunt',      'Will Grisack'),
    ('OSBORNESFURN',                               'Shindell- Beach',   'Mateo De Lisa'),
    ('JC Mattress and Furniture Showrooms',        'House',             'House'),
    ('Sundeen Furniture, Inc',                     'Skip Camillo',      'House'),
    ('Leonardo Furniture',                         'Peter Avella',      'Mateo De Lisa'),
    ('Metropolitan Furniture',                     'Andrew Smith',      'Mateo De Lisa'),
    ('Backbone Home Furnishings',                  'House',             'House'),
    ('Premium Furniture & Mattress, Inc.',         'Brent Holbrook',    'Will Grisack'),
    ('Westport Trading Company, Inc',              'Dave Ervin',        'Mateo De Lisa'),
    ('Roberts Interior Design',                    'Brent Holbrook',    'Will Grisack'),
    ('U.S. Furniture Outlet, Inc.',                'Dave Ervin',        'Mateo De Lisa'),
    ('The Rustic Mile, Inc.',                      'Stewart Hunt',      'Will Grisack'),
    ('Quality Sleep Shops of Texas',               'Stewart Hunt',      'Will Grisack'),
    ('PINKPINEAPPL',                               'Mike Durham',       'Will Grisack'),
    ('Pure Brands, LLC',                           'Brent Holbrook',    'Will Grisack'),
    ('Scott Furniture',                            'Peter Avella',      'Mateo De Lisa'),
    ('KBD Enterprises, LLC',                       'Stewart Hunt',      'Will Grisack'),
    ('Ric Burkett''s Furniture & Design',          'Brent Holbrook',    'Will Grisack'),
    ('Goffena Furniture and Mattress',             'Shindell - PA/OH',  'Mateo De Lisa'),
    ('Furniture and Beyond LLC',                   'Stewart Hunt',      'Will Grisack'),
    ('Laura Furniture Design',                     'Brent Holbrook',    'Will Grisack'),
    ('GREATBRIDGE',                                'Brad Robertson',    'Mateo De Lisa'),
    ('City Furniture Corporation',                 'Skip Camillo',      'House'),
    ('Furniture Plus, Inc.',                       'Mike Durham',       'Will Grisack'),
    ('Bazaar Investments',                         'Stewart Hunt',      'Will Grisack'),
    ('Lindsay Furniture Co.',                      'Dave Ervin',        'Mateo De Lisa'),
    ('Integrated Home LLC',                        'Shindell- Beach',   'Mateo De Lisa'),
    ('Hood Service Company',                       'Stewart Hunt',      'Will Grisack'),
    ('Robison Furniture LLC.',                     'Stewart Hunt',      'Will Grisack'),
    ('Ideal Furniture & Mattress, LLC',            'Stewart Hunt',      'Will Grisack'),
    ('Joe Bob Brown, Jr.',                         'Stewart Hunt',      'Will Grisack'),
    ('David P. Mann Jr. Family Partnership LTD.', 'Stewart Hunt',      'Will Grisack'),
    ('Rick''s Hometown TV and Appliance Center',   'Shindell - PA/OH',  'Mateo De Lisa'),
    ('Maya''s Furniture',                          'Stewart Hunt',      'Will Grisack'),
    ('Flint''s Furniture',                         'Stewart Hunt',      'Will Grisack'),
    ('Sunshine Wicker Imports',                    'Brent Holbrook',    'Will Grisack'),
    ('Florida Mattress LLC',                       'Brent Holbrook',    'Will Grisack'),
    ('Baldwin, LLC',                               'Bruce Quillen',     'Will Grisack'),
    ('Your Kitchen & Bath',                        'Skip Camillo',      'House'),
    ('Ippolito''s Furniture,Inc.',                 'Skip Camillo',      'House'),
    ('Wiggins Furniture Inc',                      'Stewart Hunt',      'Will Grisack'),
    ('Denny''s & Son''s',                          'Stewart Hunt',      'Will Grisack'),
    ('AVL Pro Inc',                                'Brent Holbrook',    'Will Grisack'),
    ('Florida Family Furniture LLC',               'Brent Holbrook',    'Will Grisack'),
    ('Lenny''s Furniture Warehouse, Inc.',         'Brent Holbrook',    'Will Grisack'),
    ('Bell''s Appliance, Inc.',                    'Mike Durham',       'Will Grisack'),
    ('Ace Integrated Technologies',                'Stewart Hunt',      'Will Grisack'),
    ('Crossroads Furniture LLC',                   'Shindell - PA/OH',  'Mateo De Lisa'),
    ('Haas-Meade Corp',                            'Brad Robertson',    'Mateo De Lisa'),
    ('Affordable Furniture for Less',              'Shindell - PA/OH',  'Mateo De Lisa'),
    ('Colony House Furniture and Bedding',         'Missouri (open)',   'Mateo De Lisa'),
    ('Furniture Plus',                             'Peter Avella',      'Mateo De Lisa'),
    ('Mattress Direct & Furniture',                'Brad Robertson',    'Mateo De Lisa')
)
UPDATE public.crm_accounts ca
SET
  assigned_rep_id     = sr.id,
  assigned_manager_id = mgr.id,
  updated_at          = now()
FROM assignments a
LEFT JOIN public.sales_reps sr  ON lower(trim(sr.name))  = lower(trim(a.rep_name))
LEFT JOIN public.managers   mgr ON lower(trim(mgr.name)) = lower(trim(a.manager_name))
WHERE lower(trim(ca.company_name)) = lower(trim(a.company_name));
